Register and Login
Tiktok-Lite/kotkit pull request #24
Opened 2023-08-11 13:53 UTC by 123ice

## 描述
请简要描述一下这个pr在原有的代码基础上做了什么改变。

## 改变的类型
- [ ] Bugfix (修改原有代码bug)

## 是否完成了测试?
- [ ] 本地接口测试

## 详细说明

2023-08-11 14:47 UTC, Centurybbx commented
由于log改成了单例模式，所以代码build没有通过，还需要改一下引用log的地方

2023-08-11 15:38 UTC, Centurybbx requested changes

2023-08-11 15:38 UTC, Centurybbx commented on config/login.yml
> +  port: 8084
由于目前端口只用了8080~8082，所以这里设置8083可能会更好

2023-08-11 15:38 UTC, Centurybbx commented on cmd/api/handler/login.go
> +			},
这里PRC错误后不处理UserID和Token的返回值是默认值吗？

2023-08-11 15:38 UTC, Centurybbx commented on cmd/api/handler/login.go
> +		},
这里同上

2023-08-11 15:38 UTC, Centurybbx commented on cmd/login/handler.go
> +	repo := repository.NewRepository(repository.DB)
这里改一下，用数据库的单例模式，参考https://github.com/Tiktok-Lite/kotkit/pull/21

2023-08-11 15:38 UTC, Centurybbx commented on cmd/login/handler.go
> +	} else if usr != nil {
上面的if中已经有return语句，这里的的else if可以换成if，逻辑更清楚

2023-08-11 15:38 UTC, Centurybbx commented on cmd/login/handler.go
> +	if err := userRepo.UpdateByUsername(req.Username,newUser); err != nil {
没太懂这里更新了什么，UserLogin应该不是User表中的字段，这样更新会改变Login中user_id外键对应User中的数据吗？

2023-08-11 15:38 UTC, Centurybbx commented on cmd/login/handler.go
> +	repo := repository.NewRepository(repository.DB)
这里的DB实例同上

2023-08-11 15:38 UTC, Centurybbx commented on cmd/login/handler.go
> +	} else if userLogin == nil {
同上

2023-08-11 16:01 UTC, 123ice commented on cmd/login/handler.go
> +	if err := userRepo.UpdateByUsername(req.Username,newUser); err != nil {
因为一开始要新建一个user,然后才能有user的id,然后有了这个id才可以新建一个login，所以就写得很绕。
然后那个userlogin我看是在user表里的。

2023-08-11 16:05 UTC, 123ice commented on cmd/api/handler/login.go
> +			},
我也不知道啊。那把这个返回值改成nil?

2023-08-12 05:32 UTC, Centurybbx approved these changes

2023-08-12 05:32 UTC, Centurybbx commented
LGTM！

2023-08-12 05:32 UTC, merged